apiVersion: v1
kind: Secret
metadata:
  name: workervotacaosecret
type: Opaque
data:
  ConnectionSqlServer: <STRING DE CONEXÃO DO SQL SERVER EM BASE 64>
  UsernameKafka: $ConnectionString
  PasswordKafka: <CONNECTION STRING DO AZURE EVENT HUBS EM BASE 64>
  SaslKafka: plaintext
  TlsKafka: enable
  AppInsightsKey: <INSTRUMENTATION KEY DO AZURE APPLICATION INSIGHTS EM BASE 64>